package common;

public abstract class StringValue {
    public static final String WELCOME = "Welcome to the course management system!";
    public static  final String ENTER_YOUR_CHOICE = "Enter your choice: ";
    public  static final String PLEASE_ENTER_VALID_INTEGER = "Please enter a valid integer.";
    public  static final String INVALID_CHOICE = "Invalid choice Please try again";
    public static final String ENTER_COURSE_CODE = "Enter course code: ";
    public static final String ENTER_COURSE_NAME = "Enter course name: ";
    public static final String ENTER_MAXIMUM_CAPACITY = "Enter maximum capacity: ";
    public static final String ENTER_STUDENT_NAME = "Enter student name: ";
    public static final String ENTER_STUDENT_ID = "Enter student ID: ";
    public static final String ENTER_GRADE = "Enter grade (eg.0 - 100): ";
    public static final String ENTER_COURSE_CODE_TO_ENROLL = "Enter course code to enroll: ";
    public static final String NO_AVAILABLE_COURSE = "No available course!";
    public static final String COURSE_CODE = "Course code: ";
    public static final String COURSE_NAME = "Course name: ";
    public static final String AVAILABLE_COURSES = "Available courses: ";
    public static final String COURSE_ALREADY_EXISTS = "Course already exists!";
    public static final String STUDENT_ALREADY_EXISTS = "Student already exists!";
    public static final String STUDENT_NOT_FOUND = "Student not found!";
    public static final String COURSE_NOT_FOUND = "Course not found!";
    public static final String STUDENT_NOT_ENROLLED = "Student not enrolled!";
    public static final String GRADE_ASSIGNED = "Grade assigned!";
    public static final String MAXIMUM_CAPACITY = "Maximum capacity: ";
    public static final String TOTAL_ENROLLED = "Total enrolled: ";
    public static final String STUDENT_ADDED = "Student added!";
    public static final String NO_STUDENT = "No student!";
    public static final String STUDENTS = "Students: ";
    public static final String STUDENT_NAME = "Student name: ";
    public static final String STUDENT_ID = "Student ID: ";
    public static final String COURSE_FULL = "Course is full!";
    public static final String ENROLL_SUCCESS = "Enroll success!";
    public static final String COURSES_ENROLLED = "Courses enrolled: ";
    public static final String STUDENT_GRADE_BOOK = "Student grade book: ";
    public static final String GRADE = "Grade: ";
    public static final String GRADE_BOOK_FOR_STUDENT = "Grade book for student: ";
    public static final String ID = "ID: ";
    public static final String AVERAGE_GRADE_FOR_COURSE = "Average grade for course: ";
}
